spring.application.name=gateway-service

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*

#################################################
# USER SERVICE
#################################################

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=citizen-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://CITIZEN-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/citizens/**

spring.cloud.gateway.server.webmvc.routes[2].id=grievance-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://GRIEVANCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/grievances/**

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8085/realms/civicpulse/protocol/openid-connect/certs

#################################################
# SERVICE MANAGEMENT SERVICE
#################################################

spring.cloud.gateway.server.webmvc.routes[3].id=service-management-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://SERVICE-MANAGEMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/certificates/**,/api/certificate/**,/api/officer/**,/api/dashboard/**,/api/documents/**