#spring.application.name=gateway-service
#
#server.port=8080
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.prefer-ip-address=true
#
##################################################
## USER SERVICE
##################################################
#
#spring.cloud.gateway.mvc.routes[0].id=user-service
#spring.cloud.gateway.mvc.routes[0].uri=lb://USER-SERVICE
#spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**
#
##################################################
## CITIZEN SERVICE
##################################################
#
#spring.cloud.gateway.mvc.routes[1].id=citizen-service
#spring.cloud.gateway.mvc.routes[1].uri=lb://CITIZEN-SERVICE
#spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/citizens/**
#
##################################################
## GRIEVANCE SERVICE
##################################################
#
#spring.cloud.gateway.mvc.routes[2].id=grievance-service
#spring.cloud.gateway.mvc.routes[2].uri=lb://GRIEVANCE-SERVICE
#spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/grievances/**
#
#management.endpoints.web.exposure.include=*
#management.endpoint.gateway.access=unrestricted

spring.application.name=gateway-service

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#################################################
# USER SERVICE
#################################################

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

#################################################
# CITIZEN SERVICE
#################################################

spring.cloud.gateway.routes[1].id=citizen-service
spring.cloud.gateway.routes[1].uri=lb://CITIZEN-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/citizens/**

#################################################
# GRIEVANCE SERVICE
#################################################

spring.cloud.gateway.routes[2].id=grievance-service
spring.cloud.gateway.routes[2].uri=lb://GRIEVANCE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/grievances/**

management.endpoints.web.exposure.include=*