spring.application.name=gateway-service

server.port=8080

#################################################
# EUREKA
#################################################

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#################################################
# ACTUATOR
#################################################

management.endpoints.web.exposure.include=*

#################################################
# USER SERVICE
#################################################

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

#################################################
# CITIZEN SERVICE
#################################################

spring.cloud.gateway.server.webmvc.routes[1].id=citizen-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://CITIZEN-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/citizens/**

#################################################
# GRIEVANCE SERVICE
#################################################

spring.cloud.gateway.server.webmvc.routes[2].id=grievance-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://GRIEVANCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/grievances/**

#################################################
# SERVICE MANAGEMENT SERVICE
#################################################

spring.cloud.gateway.server.webmvc.routes[3].id=service-management-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://SERVICE-MANAGEMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/certificates/**,/api/certificate/**,/api/officer/**,/api/dashboard/**,/api/documents/**,/api/applications/**,/api/permit/**

#################################################
# WELFARE SERVICE
#################################################

spring.cloud.gateway.server.webmvc.routes[4].id=welfare-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://WELFARE-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/welfare/**,/api/welfare-schemes/**,/api/beneficiaries/**,/api/welfare-applications/**

#################################################
# BUDGET SERVICE
#################################################

spring.cloud.gateway.server.webmvc.routes[5].id=budget-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://BUDGET-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/budget/**,/api/expenses/**,/api/fund-distributions/**,/api/analytics/**,/api/audit/**

#################################################
# KEYCLOAK JWT
#################################################

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/civicpulse/protocol/openid-connect/certs