package com.civicpulse.servicemanagement.service.impl;

import com.civicpulse.servicemanagement.entity.Application;
import com.civicpulse.servicemanagement.service.PdfService;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@Service
public class PdfServiceImpl implements PdfService {

    private static final Path PDF_FOLDER = Paths.get("certificates");

    @Override
    public String generateCertificate(Application application) {

        try {

            if (!Files.exists(PDF_FOLDER)) {
                Files.createDirectories(PDF_FOLDER);
            }

            String fileName =
                    application.getApplicationNo() + ".pdf";

            Path file = PDF_FOLDER.resolve(fileName);

            PDDocument document = new PDDocument();

            PDPage page = new PDPage();

            document.addPage(page);

            PDPageContentStream stream =
                    new PDPageContentStream(document, page);

            PDType1Font font =
                    new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);

            stream.beginText();

            stream.setFont(font, 18);

            stream.newLineAtOffset(100, 700);

            stream.showText("CIVICPULSE CERTIFICATE");

            stream.newLineAtOffset(0, -40);

            stream.showText("Application No : " + application.getApplicationNo());

            stream.newLineAtOffset(0, -25);

            stream.showText("Citizen Id : " + application.getCitizenId());

            stream.newLineAtOffset(0, -25);

            stream.showText("Certificate Type : " + application.getCertificateType());

            stream.newLineAtOffset(0, -25);

            stream.showText("Department : " + application.getDepartment());

            stream.newLineAtOffset(0, -25);

            stream.showText("Status : APPROVED");

            stream.newLineAtOffset(0, -40);

            stream.showText("Generated By CivicPulse Nexus");

            stream.endText();

            stream.close();

            document.save(file.toFile());

            document.close();

            return file.toString();

        } catch (IOException e) {

            throw new RuntimeException("Unable to generate PDF.", e);

        }
    }
}